---
title: "Waste Composition Study" 
format: revealjs
self-contained: true
editor: source
execute: 
  echo: false
  warning: false
params:
  country: "Angola"
editor_options: 
  chunk_output_type: console
---


```{r}
library(tidyverse)
```

```{r}
waste_data_long <- read_rds("data/msw-generation-and-composition-by-income-long.rds")
```

```{r}

waste_data_country <- waste_data_long %>% 
  filter(country_name == params$country)
```

# Results

## Country: `r params$country`

```{r}

ggplot(data = waste_data_country,
       mapping = aes(x = reorder(waste_category, percent), 
                     y = percent, 
                     fill = waste_category)) +
  coord_flip() +
  geom_col() +
  labs(title = paste0("Waste composition in ", params$country),
       x = NULL) +
  scale_fill_brewer(type = "qual", palette = "Paired") +
  scale_y_continuous(breaks = seq(0, 60, 5)) +
  theme_minimal(base_size = 16) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        legend.position = "none")

```

